### ISSUE TITLE
cannot import name CaffeNet in 10.17 cnn.ipynb

### ISSUE THREAD

**Issue by jiandanjinxin** [Wentong-DST/hands#1]
Hi, Wentong, thanks for your sharing. I have some problem in the 10.17 cnn.ipynb. The problem is following: 
from models import CaffeNet, InceptionResNetV2, InceptionV4 # ResNet101
ImportError: cannot import name CaffeNet, InceptionResNetV2
keras: 2.0.8   path: /usr/local/lib/python2.7/dist-packages/keras/__init__.pyc
tensorflow: 1.4.1
 models version 0.9.3  path: /usr/local/lib/python2.7/dist-packages/models/__init__.pyc

I haven't found someone having a similar problem. If possible, could you give me some tips on how to solve this problem or share with me your models version?
Thanks advance.

Albert Wang

**Comment by Wentong-DST** [comment]
Hi Albert,
Some of these models can be found in the latest Keras official repo now, or can be found via Google.
I'm going to make this repo private for a while due to project requirements.
Thank you for your interest.
Wentong
